import {
  FiMessageCircle, FiPhone, FiLink, FiFileText,
  FiSmartphone, FiVideo, FiAward, FiHeart, FiThumbsUp,
  FiShoppingBag, FiMapPin, FiCalendar, FiMessageSquare, FiInstagram,
  FiUsers, FiPlay,
} from "react-icons/fi";

// Catalogue of Meta ad types we expose in the Create Campaign launchpad.
// Each entry maps to:
//   • Meta's outcome-level objective (post-2022 ODAX taxonomy)
//   • destinationType   — drives ad-set placement & where the click lands
//   • optimizationGoal  — what the ad set optimises for
//   • cta               — Meta's call_to_action_type
//   • steps             — wizard step keys (most use the standard 4)
export const AD_TYPES = {
  whatsapp: {
    key: "whatsapp",
    title: "Click to WhatsApp",
    subtitle: "Enable direct WhatsApp conversations from your ads",
    Icon: FiMessageCircle,
    color: "#25d366",
    bg: "#d1fae5",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "WHATSAPP",
    optimizationGoal: "CONVERSATIONS",
    cta: "WHATSAPP_MESSAGE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  call: {
    key: "call",
    title: "Click to Call",
    subtitle: "Drive phone calls directly from your ads",
    Icon: FiPhone,
    color: "#f97316",
    bg: "#ffedd5",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "PHONE_CALL",
    optimizationGoal: "QUALITY_CALL",
    cta: "CALL_NOW",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  link: {
    key: "link",
    title: "Click to Website",
    subtitle: "Send traffic to your landing page or website",
    Icon: FiLink,
    color: "#ec4899",
    bg: "#fce7f3",
    objective: "OUTCOME_TRAFFIC",
    destinationType: "WEBSITE",
    optimizationGoal: "LINK_CLICKS",
    cta: "LEARN_MORE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  leadform: {
    key: "leadform",
    title: "Lead Form Ads",
    subtitle: "Collect leads natively via Meta Lead Forms",
    Icon: FiFileText,
    color: "#3b82f6",
    bg: "#dbeafe",
    objective: "OUTCOME_LEADS",
    destinationType: "ON_AD",
    optimizationGoal: "LEAD_GENERATION",
    cta: "SIGN_UP",
    steps: ["campaign", "form", "adset", "creative", "launch"],
  },

  // ---- Awareness & reach ----
  awareness: {
    key: "awareness",
    title: "Brand Awareness",
    subtitle: "Show your ad to people most likely to remember it",
    Icon: FiAward,
    color: "#8b5cf6",
    bg: "#ede9fe",
    objective: "OUTCOME_AWARENESS",
    destinationType: "WEBSITE",
    optimizationGoal: "AD_RECALL_LIFT",
    cta: "LEARN_MORE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  reach: {
    key: "reach",
    title: "Reach",
    subtitle: "Show your ad to the maximum number of people",
    Icon: FiUsers,
    color: "#a78bfa",
    bg: "#ede9fe",
    objective: "OUTCOME_AWARENESS",
    destinationType: "WEBSITE",
    optimizationGoal: "REACH",
    cta: "LEARN_MORE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  video: {
    key: "video",
    title: "Video Views",
    subtitle: "Get more people to watch your video",
    Icon: FiVideo,
    color: "#f43f5e",
    bg: "#ffe4e6",
    objective: "OUTCOME_AWARENESS",
    destinationType: "WEBSITE",
    optimizationGoal: "THRUPLAY",
    cta: "WATCH_MORE",
    steps: ["campaign", "adset", "creative", "launch"],
  },

  // ---- Engagement extras ----
  postEngagement: {
    key: "postEngagement",
    title: "Post Engagement",
    subtitle: "Boost a post for more reactions, comments & shares",
    Icon: FiHeart,
    color: "#ef4444",
    bg: "#fee2e2",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "ON_POST",
    optimizationGoal: "POST_ENGAGEMENT",
    cta: "LIKE_PAGE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  pageLikes: {
    key: "pageLikes",
    title: "Page Likes",
    subtitle: "Grow your Facebook page's audience",
    Icon: FiThumbsUp,
    color: "#1877f2",
    bg: "#dbeafe",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "ON_PAGE",
    optimizationGoal: "PAGE_LIKES",
    cta: "LIKE_PAGE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  messenger: {
    key: "messenger",
    title: "Click to Messenger",
    subtitle: "Start Messenger conversations from your ads",
    Icon: FiMessageSquare,
    color: "#0084ff",
    bg: "#dbeafe",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "MESSENGER",
    optimizationGoal: "CONVERSATIONS",
    cta: "MESSAGE_PAGE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  instagramDm: {
    key: "instagramDm",
    title: "Instagram DMs",
    subtitle: "Spark conversations in Instagram Direct",
    Icon: FiInstagram,
    color: "#e1306c",
    bg: "#fce7f3",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "INSTAGRAM_DIRECT",
    optimizationGoal: "CONVERSATIONS",
    cta: "INSTAGRAM_MESSAGE",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  event: {
    key: "event",
    title: "Event Responses",
    subtitle: "Get more RSVPs to your Facebook event",
    Icon: FiCalendar,
    color: "#0ea5e9",
    bg: "#e0f2fe",
    objective: "OUTCOME_ENGAGEMENT",
    destinationType: "ON_EVENT",
    optimizationGoal: "EVENT_RESPONSES",
    cta: "GET_DIRECTIONS",
    steps: ["campaign", "adset", "creative", "launch"],
  },

  // ---- Sales / commerce ----
  catalogSales: {
    key: "catalogSales",
    title: "Catalog Sales",
    subtitle: "Promote products from your Meta product catalog",
    Icon: FiShoppingBag,
    color: "#10b981",
    bg: "#d1fae5",
    objective: "OUTCOME_SALES",
    destinationType: "WEBSITE",
    optimizationGoal: "OFFSITE_CONVERSIONS",
    cta: "SHOP_NOW",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  storeVisits: {
    key: "storeVisits",
    title: "Store Traffic",
    subtitle: "Drive footfall to your nearby store locations",
    Icon: FiMapPin,
    color: "#22c55e",
    bg: "#dcfce7",
    objective: "OUTCOME_AWARENESS",
    destinationType: "WEBSITE",
    optimizationGoal: "STORE_VISITS",
    cta: "GET_DIRECTIONS",
    steps: ["campaign", "adset", "creative", "launch"],
  },

  // ---- App promotion ----
  appInstall: {
    key: "appInstall",
    title: "App Installs",
    subtitle: "Drive installs of your iOS / Android app",
    Icon: FiSmartphone,
    color: "#6366f1",
    bg: "#e0e7ff",
    objective: "OUTCOME_APP_PROMOTION",
    destinationType: "APP",
    optimizationGoal: "APP_INSTALLS",
    cta: "INSTALL_MOBILE_APP",
    steps: ["campaign", "adset", "creative", "launch"],
  },
  appEngagement: {
    key: "appEngagement",
    title: "App Engagement",
    subtitle: "Re-engage existing app users to take an action",
    Icon: FiPlay,
    color: "#7c3aed",
    bg: "#ede9fe",
    objective: "OUTCOME_APP_PROMOTION",
    destinationType: "APP",
    optimizationGoal: "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
    cta: "USE_MOBILE_APP",
    steps: ["campaign", "adset", "creative", "launch"],
  },
};

export function stepIndex(type, step) {
  const cfg = AD_TYPES[type];
  if (!cfg) return -1;
  return cfg.steps.indexOf(step);
}

export function stepLabel(step) {
  return {
    campaign: "Campaign",
    form:     "Lead form",
    adset:    "Ad set",
    creative: "Creative",
    launch:   "Launch",
  }[step] || step;
}
