import { useEffect, useState } from "react";
import { FiFileText, FiRefreshCw, FiDownload } from "react-icons/fi";
import { pricingApi } from "../../api/pricing";

export default function Invoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function load() {
    setLoading(true); setError("");
    try {
      const res = await pricingApi.invoices();
      setInvoices(res.invoices || []);
    } catch (err) { setError(err.message); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  function downloadInvoice(inv) {
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice ${inv.number}</title>
<style>body{font-family:'Inter',system-ui,sans-serif;padding:40px;color:#111;max-width:760px;margin:0 auto}
h1{color:#7c3aed;font-size:28px;margin-bottom:6px}.muted{color:#6b7280;font-size:13px}
table{width:100%;margin-top:30px;border-collapse:collapse}
th,td{padding:12px;text-align:left;border-bottom:1px solid #e5e7eb}th{background:#faf5ff;font-size:11px;text-transform:uppercase;color:#6b7280}
.total{font-size:22px;font-weight:800;color:#7c3aed;text-align:right;padding-top:14px;border-top:2px solid #111}</style></head>
<body><h1>INVOICE</h1><div class="muted">#${inv.number}</div>
<div style="margin-top:18px;padding:14px 0;border-top:1px solid #e5e7eb;border-bottom:1px solid #e5e7eb">
<strong>${inv.planName}</strong> · ${inv.duration} subscription<br><span class="muted">Paid on ${new Date(inv.paidAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</span></div>
<table><thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
<tbody><tr><td>${inv.planName} subscription (${inv.duration})</td><td style="text-align:right">₹${inv.amount.toLocaleString()}</td></tr></tbody></table>
<div class="total" style="margin-top:14px">Total ₹${inv.amount.toLocaleString()} ${inv.currency}</div>
<p class="muted" style="margin-top:30px;text-align:center">Razorpay payment ID: ${inv.razorpayPaymentId || "—"}</p>
<p class="muted" style="text-align:center;margin-top:20px;border-top:1px solid #f3f4f6;padding-top:14px">Generated by Leadnator · leadnator.app</p></body></html>`;
    const w = window.open("", "_blank", "width=900,height=1100");
    if (!w) return alert("Allow pop-ups to download the invoice.");
    w.document.write(html); w.document.close();
    setTimeout(() => w.print(), 300);
  }

  return (
    <>
      <h1 className="page-title">Invoices</h1>
      <p className="page-subtitle">All invoices for your account.</p>

      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 14 }}>
        <button className="btn btn-outline" onClick={load}><FiRefreshCw /> Refresh</button>
      </div>

      {error && <div style={{ padding: 12, background: "#fee2e2", color: "#b91c1c", borderRadius: 8, marginBottom: 12, fontSize: 13 }}>{error}</div>}

      <div className="card" style={{ padding: 0 }}>
        <div style={{ padding: "16px 20px", borderBottom: "1px solid var(--border)" }} className="card-title">
          <FiFileText style={{ verticalAlign: "middle" }} /> {invoices.length} invoice{invoices.length === 1 ? "" : "s"}
        </div>
        <div className="table-wrap">
          <table>
            <thead><tr><th>Invoice</th><th>Plan</th><th>Date</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead>
            <tbody>
              {loading ? (
                <tr><td colSpan="6" style={{ textAlign: "center", padding: 30, color: "var(--text-muted)" }}>Loading…</td></tr>
              ) : invoices.length === 0 ? (
                <tr><td colSpan="6" style={{ textAlign: "center", padding: 30, color: "var(--text-muted)" }}>No invoices yet.</td></tr>
              ) : invoices.map((inv) => (
                <tr key={inv.id}>
                  <td style={{ fontFamily: "monospace", fontSize: 12 }}>{inv.number}</td>
                  <td><strong>{inv.planName}</strong> <span style={{ fontSize: 11, color: "var(--text-muted)" }}>· {inv.duration}</span></td>
                  <td style={{ color: "var(--text-muted)" }}>
                    {new Date(inv.paidAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}
                  </td>
                  <td style={{ fontWeight: 700 }}>₹{inv.amount.toLocaleString()}</td>
                  <td><span className={`badge ${inv.status === "paid" ? "qualified" : inv.status === "failed" ? "lost" : "contacted"}`}>{inv.status}</span></td>
                  <td><button className="btn btn-outline" onClick={() => downloadInvoice(inv)}><FiDownload /> Download PDF</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
