/**
 * Example WhatsApp template definitions for the "Import existing example" library.
 * Names are suggestions (snake_case); users should adjust before submit to avoid duplicates on their WABA.
 * All templates use language "en_US" and do NOT end with a variable placeholder.
 */

export const UTILITY_TEMPLATE_EXAMPLES = [
  {
    id: "u1",
    title: "Order shipped",
    description: "Shipping notification with tracking",
    name: "utility_order_shipped_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your order {{order_id}} has shipped! Track your delivery here: {{tracking_url}}. We hope you enjoy your purchase.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Asha" },
      { name: "{{order_id}}", example: "#88291" },
      { name: "{{tracking_url}}", example: "https://track.example.com/abc" },
    ],
    bodyExample: "",
  },
  {
    id: "u2",
    title: "Order delivered",
    description: "Delivery confirmation",
    name: "utility_order_delivered_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hello {{customer_name}}, your order {{order_id}} was delivered on {{delivery_date}}. We hope you love it!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Rahul" },
      { name: "{{order_id}}", example: "#44102" },
      { name: "{{delivery_date}}", example: "6 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "u3",
    title: "Appointment reminder",
    description: "Upcoming appointment",
    name: "utility_appt_reminder_01",
    category: "UTILITY",
    language: "en_US",
    body: "Reminder: Hi {{customer_name}}, you have an appointment on {{date}} at {{time}} with {{provider_name}}. Please arrive 5 minutes early.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Priya" },
      { name: "{{date}}", example: "8 Apr 2026" },
      { name: "{{time}}", example: "3:00 PM" },
      { name: "{{provider_name}}", example: "Dr. Mehta" },
    ],
    bodyExample: "",
  },
  {
    id: "u4",
    title: "Payment received",
    description: "Payment confirmation",
    name: "utility_payment_received_01",
    category: "UTILITY",
    language: "en_US",
    body: "We received {{amount}} for invoice {{invoice_id}} on {{payment_date}}. Thank you, {{customer_name}} — your account is up to date.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{amount}}", example: "₹2,499" },
      { name: "{{invoice_id}}", example: "INV-2026-004" },
      { name: "{{payment_date}}", example: "5 Apr 2026" },
      { name: "{{customer_name}}", example: "Vikram" },
    ],
    bodyExample: "",
  },
  {
    id: "u5",
    title: "Booking confirmed",
    description: "Reservation confirmation",
    name: "utility_booking_confirmed_01",
    category: "UTILITY",
    language: "en_US",
    body: "Your booking is confirmed, {{customer_name}}! Service: {{service_name}} on {{booking_date}}. Your reference number is {{booking_ref}}. See you soon!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Neha" },
      { name: "{{service_name}}", example: "Spa — 60 min" },
      { name: "{{booking_date}}", example: "10 Apr 2026, 11 AM" },
      { name: "{{booking_ref}}", example: "BK-99321" },
    ],
    bodyExample: "",
  },
  {
    id: "u6",
    title: "Delivery ETA",
    description: "Updated arrival window",
    name: "utility_delivery_eta_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your package {{order_id}} is out for delivery today. Estimated arrival: {{eta_window}}. Please ensure someone is available to receive it.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Sanjay" },
      { name: "{{order_id}}", example: "#77123" },
      { name: "{{eta_window}}", example: "Today 4–6 PM" },
    ],
    bodyExample: "",
  },
  {
    id: "u7",
    title: "Subscription renewal",
    description: "Renewal reminder (non-promotional)",
    name: "utility_subscription_renew_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{plan_name}} subscription renews on {{renewal_date}} for {{amount}}. No action needed if you wish to continue.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Anita" },
      { name: "{{plan_name}}", example: "Pro Annual" },
      { name: "{{renewal_date}}", example: "15 Apr 2026" },
      { name: "{{amount}}", example: "₹4,999" },
    ],
    bodyExample: "",
  },
  {
    id: "u8",
    title: "Support ticket update",
    description: "Ticket status change",
    name: "utility_ticket_update_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, there's an update on your ticket {{ticket_id}}: {{status_message}}. Our team is working hard to resolve this for you.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Kiran" },
      { name: "{{ticket_id}}", example: "#45821" },
      { name: "{{status_message}}", example: "Our team is reviewing your case" },
    ],
    bodyExample: "",
  },
  {
    id: "u9",
    title: "Invoice ready",
    description: "Invoice available",
    name: "utility_invoice_ready_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your invoice {{invoice_id}} for {{amount}} is ready. Download it from your account portal or reply to this message for assistance.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Deepak" },
      { name: "{{invoice_id}}", example: "INV-7781" },
      { name: "{{amount}}", example: "₹12,400" },
    ],
    bodyExample: "",
  },
  {
    id: "u10",
    title: "Account security alert",
    description: "Login or security notice",
    name: "utility_security_notice_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, we noticed a sign-in to your account from {{location}} at {{time}}. If this wasn't you, please contact support immediately.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Ravi" },
      { name: "{{location}}", example: "Mumbai, IN" },
      { name: "{{time}}", example: "5 Apr 2026, 9:12 PM" },
    ],
    bodyExample: "",
  },
  {
    id: "u11",
    title: "Table ready",
    description: "Restaurant seating",
    name: "utility_table_ready_01",
    category: "UTILITY",
    language: "en_US",
    body: "Great news {{customer_name}}, your table for {{party_size}} is ready at {{restaurant_name}}. Please arrive within {{minutes}} minutes or your reservation may be released.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Meera" },
      { name: "{{party_size}}", example: "4 guests" },
      { name: "{{restaurant_name}}", example: "Spice Route" },
      { name: "{{minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "u12",
    title: "Pickup ready",
    description: "Order ready for pickup",
    name: "utility_pickup_ready_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hello {{customer_name}}, order {{order_id}} is ready for pickup at {{store_name}}. Location: {{store_address}}. We look forward to seeing you!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Arjun" },
      { name: "{{order_id}}", example: "#P-992" },
      { name: "{{store_name}}", example: "City Center Outlet" },
      { name: "{{store_address}}", example: "12 MG Road" },
    ],
    bodyExample: "",
  },
  {
    id: "u13",
    title: "Class schedule change",
    description: "Session update",
    name: "utility_class_update_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{student_name}}, {{class_name}} on {{original_date}} has been moved to {{new_date}}. Reason: {{reason}}. We apologize for any inconvenience.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{student_name}}", example: "Isha" },
      { name: "{{class_name}}", example: "Yoga L2" },
      { name: "{{original_date}}", example: "7 Apr" },
      { name: "{{new_date}}", example: "9 Apr, 6 PM" },
      { name: "{{reason}}", example: "Instructor availability" },
    ],
    bodyExample: "",
  },
  {
    id: "u14",
    title: "Membership expiring",
    description: "Expiry reminder",
    name: "utility_membership_expiry_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{membership_type}} membership expires on {{expiry_date}}. Renew now to keep uninterrupted access to all your benefits.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Omar" },
      { name: "{{membership_type}}", example: "Gold" },
      { name: "{{expiry_date}}", example: "30 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "u15",
    title: "Refund processed",
    description: "Refund confirmation",
    name: "utility_refund_done_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your refund of {{amount}} for order {{order_id}} has been processed successfully. It may take {{days}} business days to reflect in your account.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Sneha" },
      { name: "{{amount}}", example: "₹899" },
      { name: "{{order_id}}", example: "#55102" },
      { name: "{{days}}", example: "5–7" },
    ],
    bodyExample: "",
  },
  {
    id: "u16",
    title: "Document received",
    description: "Upload acknowledgement",
    name: "utility_document_received_01",
    category: "UTILITY",
    language: "en_US",
    body: "Thanks {{customer_name}}! We received your {{document_type}} for application {{application_id}}. Next step: {{next_step}}. We'll keep you updated.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Leela" },
      { name: "{{document_type}}", example: "ID proof" },
      { name: "{{application_id}}", example: "APP-221" },
      { name: "{{next_step}}", example: "Verification within 2 days" },
    ],
    bodyExample: "",
  },
  {
    id: "u17",
    title: "Service completed",
    description: "Job / service done",
    name: "utility_service_completed_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{service_name}} scheduled on {{service_date}} is now complete. Reference: {{job_id}}. Thank you for choosing us!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Harsh" },
      { name: "{{service_name}}", example: "AC servicing" },
      { name: "{{service_date}}", example: "5 Apr 2026" },
      { name: "{{job_id}}", example: "JOB-8831" },
    ],
    bodyExample: "",
  },
  {
    id: "u18",
    title: "OTP / code delivery (utility context)",
    description: "Transactional code (use AUTH category in production if required)",
    name: "utility_action_code_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, use code {{code}} to {{action}}. This code expires in {{minutes}} minutes. Do not share this code with anyone.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Nina" },
      { name: "{{code}}", example: "482910" },
      { name: "{{action}}", example: "confirm your update" },
      { name: "{{minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "u19",
    title: "Hotel check-in info",
    description: "Pre-arrival details",
    name: "utility_hotel_checkin_01",
    category: "UTILITY",
    language: "en_US",
    body: "Dear {{guest_name}}, your check-in for booking {{confirmation_code}} is on {{checkin_date}} from {{checkin_time}}. Hotel address: {{hotel_address}}. We look forward to welcoming you!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{guest_name}}", example: "Mr. Kapoor" },
      { name: "{{confirmation_code}}", example: "HTL-9921" },
      { name: "{{checkin_date}}", example: "12 Apr 2026" },
      { name: "{{checkin_time}}", example: "2:00 PM" },
      { name: "{{hotel_address}}", example: "88 Marine Drive" },
    ],
    bodyExample: "",
  },
  {
    id: "u20",
    title: "Prescription / order ready (pickup)",
    description: "Pharmacy / lab style",
    name: "utility_order_ready_pickup_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hello {{customer_name}}, your {{item_type}} (ref: {{reference_id}}) is ready for pickup at {{location_name}}. Store hours: {{hours}}. Please bring a valid ID.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Geeta" },
      { name: "{{item_type}}", example: "prescription order" },
      { name: "{{reference_id}}", example: "RX-441" },
      { name: "{{location_name}}", example: "HealthPlus Sector 18" },
      { name: "{{hours}}", example: "9 AM – 9 PM" },
    ],
    bodyExample: "",
  },
  {
    id: "u21",
    title: "Loan EMI reminder",
    description: "Upcoming loan installment",
    name: "utility_loan_emi_reminder_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your EMI of {{amount}} for loan {{loan_id}} is due on {{due_date}}. Please ensure your account has sufficient balance.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Anita" },
      { name: "{{amount}}", example: "₹12,500" },
      { name: "{{loan_id}}", example: "LN-9921" },
      { name: "{{due_date}}", example: "5 May 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "u22",
    title: "KYC document required",
    description: "Action needed to complete KYC",
    name: "utility_kyc_required_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, we need {{document_name}} to complete your KYC. Please upload it here: {{upload_link}} within {{deadline}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Rohit" },
      { name: "{{document_name}}", example: "Aadhaar card" },
      { name: "{{upload_link}}", example: "https://leadnator.app/kyc/abc" },
      { name: "{{deadline}}", example: "7 days" },
    ],
    bodyExample: "",
  },
  {
    id: "u23",
    title: "Order out for delivery",
    description: "Driver assigned, ETA shared",
    name: "utility_out_for_delivery_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, order {{order_id}} is out for delivery. Driver: {{driver_name}} ({{driver_phone}}). ETA: {{eta}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Sneha" },
      { name: "{{order_id}}", example: "#88301" },
      { name: "{{driver_name}}", example: "Kiran" },
      { name: "{{driver_phone}}", example: "+91 98xxxxxxxx" },
      { name: "{{eta}}", example: "5:30 PM" },
    ],
    bodyExample: "",
  },
  {
    id: "u24",
    title: "Test results ready",
    description: "Lab / report ready notice",
    name: "utility_test_results_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hello {{customer_name}}, your {{test_name}} report is ready. Download it here: {{report_link}}. Reach out to {{contact}} if you have questions.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Arjun" },
      { name: "{{test_name}}", example: "Blood test" },
      { name: "{{report_link}}", example: "https://lab.example.com/r/4521" },
      { name: "{{contact}}", example: "+91 99xxxxxxxx" },
    ],
    bodyExample: "",
  },
  {
    id: "u25",
    title: "Booking modified",
    description: "Confirms a change to a booking",
    name: "utility_booking_modified_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your booking {{booking_id}} has been updated. New details: {{new_details}}. If this is wrong, reply REVERT.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Kavya" },
      { name: "{{booking_id}}", example: "BK-7710" },
      { name: "{{new_details}}", example: "10 Jun, 7:30 PM, table for 4" },
    ],
    bodyExample: "",
  },
  {
    id: "u26",
    title: "Service technician on the way",
    description: "Field service ETA",
    name: "utility_technician_eta_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, our technician {{technician_name}} is on the way for your {{service_type}} service. ETA: {{eta}} mins.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Mohit" },
      { name: "{{technician_name}}", example: "Suresh" },
      { name: "{{service_type}}", example: "AC repair" },
      { name: "{{eta}}", example: "20" },
    ],
    bodyExample: "",
  },
  {
    id: "u27",
    title: "Renewal in 7 days",
    description: "Subscription about to renew",
    name: "utility_renewal_warning_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{plan_name}} plan renews on {{renewal_date}} for {{amount}}. Manage your subscription: {{manage_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Pooja" },
      { name: "{{plan_name}}", example: "Growth" },
      { name: "{{renewal_date}}", example: "12 May 2026" },
      { name: "{{amount}}", example: "₹499" },
      { name: "{{manage_link}}", example: "https://leadnator.app/billing" },
    ],
    bodyExample: "",
  },
  {
    id: "u28",
    title: "Profile update confirmation",
    description: "Confirms an account change",
    name: "utility_profile_updated_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{updated_field}} was updated successfully on {{updated_at}}. If you didn't make this change, contact support.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Karan" },
      { name: "{{updated_field}}", example: "email address" },
      { name: "{{updated_at}}", example: "19 Apr 2026, 11:42 AM" },
    ],
    bodyExample: "",
  },
  {
    id: "u29",
    title: "Cancellation confirmed",
    description: "Order / booking cancellation",
    name: "utility_cancelled_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{item_type}} {{reference_id}} has been cancelled. Any payment of {{amount}} will be refunded within {{refund_window}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Isha" },
      { name: "{{item_type}}", example: "order" },
      { name: "{{reference_id}}", example: "#88122" },
      { name: "{{amount}}", example: "₹1,899" },
      { name: "{{refund_window}}", example: "5–7 business days" },
    ],
    bodyExample: "",
  },
  {
    id: "u30",
    title: "Dispute / claim status",
    description: "Status update on a complaint",
    name: "utility_dispute_status_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your dispute {{ticket_id}} is now {{status}}. Resolution: {{resolution_note}}. View details: {{ticket_url}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Vivek" },
      { name: "{{ticket_id}}", example: "DSP-22198" },
      { name: "{{status}}", example: "approved" },
      { name: "{{resolution_note}}", example: "We've credited the amount back to your wallet." },
      { name: "{{ticket_url}}", example: "https://leadnator.app/help/22198" },
    ],
    bodyExample: "",
  },
];

export const MARKETING_TEMPLATE_EXAMPLES = [
  {
    id: "m1",
    title: "Flash sale",
    description: "Short limited offer",
    name: "mkt_flash_sale_01",
    category: "MARKETING",
    language: "en_US",
    body: "⚡ Flash sale! Hi {{customer_name}}, get {{discount}} off {{product_line}} until {{end_time}}. Don't miss out — shop now!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "friend" },
      { name: "{{discount}}", example: "30%" },
      { name: "{{product_line}}", example: "all sneakers" },
      { name: "{{end_time}}", example: "midnight tonight" },
    ],
    bodyExample: "",
  },
  {
    id: "m2",
    title: "New collection",
    description: "Launch announcement",
    name: "mkt_new_collection_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, our {{collection_name}} collection just dropped! Explore {{highlight}} and find your new favourite — link in our profile.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "style lover" },
      { name: "{{collection_name}}", example: "Summer Breeze" },
      { name: "{{highlight}}", example: "linen sets & dresses" },
    ],
    bodyExample: "",
  },
  {
    id: "m3",
    title: "Seasonal discount",
    description: "Season / festival tie-in",
    name: "mkt_seasonal_01",
    category: "MARKETING",
    language: "en_US",
    body: "Celebrate {{festival_name}} with us, {{customer_name}}! Enjoy {{offer_text}}. Hurry — offer valid only till {{valid_until}}. Shop now!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{festival_name}}", example: "Eid" },
      { name: "{{customer_name}}", example: "Zara" },
      { name: "{{offer_text}}", example: "Extra 15% on orders above ₹1999" },
      { name: "{{valid_until}}", example: "14 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m4",
    title: "Cart reminder",
    description: "Abandoned cart nudge",
    name: "mkt_cart_reminder_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, you left {{item_summary}} in your cart. Complete your checkout using code {{coupon_code}} for an extra discount. Your cart is waiting!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{item_summary}}", example: "3 items" },
      { name: "{{coupon_code}}", example: "SAVE10" },
    ],
    bodyExample: "",
  },
  {
    id: "m5",
    title: "Birthday offer",
    description: "Birthday promo",
    name: "mkt_birthday_01",
    category: "MARKETING",
    language: "en_US",
    body: "Happy Birthday {{customer_name}}! 🎂 Enjoy {{gift_offer}} on us — our gift to you. Offer valid until {{expiry_date}}. Celebrate in style!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Aditya" },
      { name: "{{gift_offer}}", example: "20% off your next order" },
      { name: "{{expiry_date}}", example: "30 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m6",
    title: "Webinar invite",
    description: "Event registration push",
    name: "mkt_webinar_01",
    category: "MARKETING",
    language: "en_US",
    body: "You're invited, {{customer_name}}! Join us for {{webinar_title}} on {{event_date}} at {{event_time}}. Save your seat before it fills up!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "marketer" },
      { name: "{{webinar_title}}", example: "Growth Hacking 101" },
      { name: "{{event_date}}", example: "18 Apr 2026" },
      { name: "{{event_time}}", example: "5 PM IST" },
    ],
    bodyExample: "",
  },
  {
    id: "m7",
    title: "Loyalty points",
    description: "Rewards update",
    name: "mkt_loyalty_points_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, you have {{points}} points in your {{tier}} tier account. {{reward_teaser}} — keep shopping to unlock more rewards!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "loyal shopper" },
      { name: "{{points}}", example: "2,400" },
      { name: "{{tier}}", example: "Gold" },
      { name: "{{reward_teaser}}", example: "Unlock free shipping at 3,000 pts" },
    ],
    bodyExample: "",
  },
  {
    id: "m8",
    title: "Referral reward",
    description: "Refer-a-friend",
    name: "mkt_referral_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hey {{customer_name}}, refer friends and earn {{reward_amount}} for every successful signup. Share your unique code {{referral_code}} and start earning today!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "champion" },
      { name: "{{reward_amount}}", example: "₹200" },
      { name: "{{referral_code}}", example: "ASHA-77" },
    ],
    bodyExample: "",
  },
  {
    id: "m9",
    title: "Back in stock",
    description: "Restock alert",
    name: "mkt_back_in_stock_01",
    category: "MARKETING",
    language: "en_US",
    body: "Good news {{customer_name}}! {{product_name}} is back in stock. Only {{stock_note}} available — grab yours before it sells out again!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{product_name}}", example: "Pro Wireless Earbuds" },
      { name: "{{stock_note}}", example: "limited units" },
    ],
    bodyExample: "",
  },
  {
    id: "m10",
    title: "Free trial ending",
    description: "Upgrade CTA",
    name: "mkt_trial_ending_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, your {{plan_name}} trial ends on {{end_date}}. Upgrade now and take advantage of {{offer_summary}}. Don't lose your progress!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "builder" },
      { name: "{{plan_name}}", example: "Pro" },
      { name: "{{end_date}}", example: "20 Apr 2026" },
      { name: "{{offer_summary}}", example: "20% off first paid month" },
    ],
    bodyExample: "",
  },
  {
    id: "m11",
    title: "Newsletter / digest",
    description: "Weekly roundup",
    name: "mkt_newsletter_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, this week on {{brand_name}}: {{headline_1}} • {{headline_2}} • and much more. Tap the link in our profile to read the full digest.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "reader" },
      { name: "{{brand_name}}", example: "Acme Blog" },
      { name: "{{headline_1}}", example: "5 new guides" },
      { name: "{{headline_2}}", example: "Product tips" },
    ],
    bodyExample: "",
  },
  {
    id: "m12",
    title: "Event promo",
    description: "In-store / online event",
    name: "mkt_event_promo_01",
    category: "MARKETING",
    language: "en_US",
    body: "Join us {{customer_name}}! We're hosting {{event_name}} on {{event_date}} at {{venue}}. Perks include: {{perks}}. We'd love to see you there!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{event_name}}", example: "Spring Pop-up" },
      { name: "{{event_date}}", example: "22 Apr 2026" },
      { name: "{{venue}}", example: "DLF Mall" },
      { name: "{{perks}}", example: "Free tote + snacks" },
    ],
    bodyExample: "",
  },
  {
    id: "m13",
    title: "App install push",
    description: "Download app",
    name: "mkt_app_download_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, order faster with the {{app_name}} app! {{incentive}}. Search for {{app_name}} on your app store and download it today.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "shopper" },
      { name: "{{app_name}}", example: "FreshCart" },
      { name: "{{incentive}}", example: "First app order: free delivery" },
    ],
    bodyExample: "",
  },
  {
    id: "m14",
    title: "Feedback + reward",
    description: "Survey with perk",
    name: "mkt_feedback_reward_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, we'd love your feedback on {{topic}}. {{reward_line}}. Your opinion helps us serve you better — thank you!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{topic}}", example: "your recent purchase" },
      { name: "{{reward_line}}", example: "Complete a 2-min survey & get 50 loyalty points" },
    ],
    bodyExample: "",
  },
  {
    id: "m15",
    title: "Win-back offer",
    description: "Re-engage inactive users",
    name: "mkt_winback_01",
    category: "MARKETING",
    language: "en_US",
    body: "We miss you {{customer_name}}! Come back and enjoy {{offer_detail}}. This exclusive offer expires on {{deadline}} — we'd love to have you back!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{offer_detail}}", example: "25% off your next order" },
      { name: "{{deadline}}", example: "30 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m16",
    title: "Bundle deal",
    description: "Combo offer",
    name: "mkt_bundle_01",
    category: "MARKETING",
    language: "en_US",
    body: "Bundle alert! Hi {{customer_name}}, get the {{bundle_name}} for just {{bundle_price}} and save {{savings}}. Perfect for {{use_case}} — limited time only!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "you" },
      { name: "{{bundle_name}}", example: "Starter Kit Pack" },
      { name: "{{bundle_price}}", example: "₹1,999" },
      { name: "{{savings}}", example: "₹500" },
      { name: "{{use_case}}", example: "home office" },
    ],
    bodyExample: "",
  },
  {
    id: "m17",
    title: "Limited coupon",
    description: "Code drop",
    name: "mkt_coupon_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, your exclusive code {{coupon_code}} gives {{discount}} off on orders above {{min_order}}. Offer expires {{end_date}} — use it before it's gone!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "VIP" },
      { name: "{{coupon_code}}", example: "VIPAPR20" },
      { name: "{{discount}}", example: "20%" },
      { name: "{{min_order}}", example: "₹999" },
      { name: "{{end_date}}", example: "25 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m18",
    title: "Social proof sale",
    description: "Trending / bestseller",
    name: "mkt_social_proof_01",
    category: "MARKETING",
    language: "en_US",
    body: "Trending now: {{product_name}} — already loved by {{customer_count}}+ happy customers! Hi {{customer_name}}, find out why everyone is talking about it.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{product_name}}", example: "Glow Serum" },
      { name: "{{customer_count}}", example: "12,000" },
      { name: "{{customer_name}}", example: "there" },
    ],
    bodyExample: "",
  },
  {
    id: "m19",
    title: "Partner / collab promo",
    description: "Co-marketing",
    name: "mkt_partner_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hey {{customer_name}}, {{brand_a}} x {{brand_b}} have teamed up! {{offer_text}}. Don't miss {{highlight}} — this collab won't last long.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{brand_a}}", example: "FitFuel" },
      { name: "{{brand_b}}", example: "RunClub" },
      { name: "{{offer_text}}", example: "Joint membership at ₹999/mo" },
      { name: "{{highlight}}", example: "first 100 signups" },
    ],
    bodyExample: "",
  },
  {
    id: "m20",
    title: "Holiday campaign",
    description: "Holiday-themed promo",
    name: "mkt_holiday_01",
    category: "MARKETING",
    language: "en_US",
    body: "Wishing you a wonderful season, {{customer_name}}! {{promo_line}} Shop {{category}} with code {{code}} and make this season extra special. Happy celebrating!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "there" },
      { name: "{{promo_line}}", example: "Enjoy up to 40% off gifts." },
      { name: "{{category}}", example: "home & decor" },
      { name: "{{code}}", example: "HOLIDAY40" },
    ],
    bodyExample: "",
  },
  {
    id: "m21",
    title: "Early bird discount",
    description: "Pre-launch / early access offer",
    name: "mkt_early_bird_01",
    category: "MARKETING",
    language: "en_US",
    body: "🔔 Early bird, {{customer_name}}! Be among the first {{slots}} to grab {{product_name}} at {{discount}} off. Use code {{code}} before the regular launch.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Aarav" },
      { name: "{{slots}}", example: "100" },
      { name: "{{product_name}}", example: "Pro Plan" },
      { name: "{{discount}}", example: "30%" },
      { name: "{{code}}", example: "EARLY30" },
    ],
    bodyExample: "",
  },
  {
    id: "m22",
    title: "Bundle upgrade",
    description: "Cross-sell to existing customers",
    name: "mkt_bundle_upgrade_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, upgrade to the {{bundle_name}} bundle and save {{savings}} vs buying separately. Limited to {{deadline}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Priya" },
      { name: "{{bundle_name}}", example: "Growth + AI Add-on" },
      { name: "{{savings}}", example: "₹1,200" },
      { name: "{{deadline}}", example: "30 Apr 2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m23",
    title: "Daily deal",
    description: "Today-only offer",
    name: "mkt_daily_deal_01",
    category: "MARKETING",
    language: "en_US",
    body: "🔥 Today only: {{product_name}} for {{price}}. Use code {{code}} at checkout. Offer ends {{end_time}} — don't miss out!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{product_name}}", example: "Annual Pro" },
      { name: "{{price}}", example: "₹9,990" },
      { name: "{{code}}", example: "TODAY10" },
      { name: "{{end_time}}", example: "11:59 PM IST" },
    ],
    bodyExample: "",
  },
  {
    id: "m24",
    title: "Seasonal lookbook",
    description: "Collection / catalog tease",
    name: "mkt_lookbook_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, our {{season}} {{collection_name}} is here. Browse {{look_count}} new looks: {{lookbook_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Neha" },
      { name: "{{season}}", example: "Summer 2026" },
      { name: "{{collection_name}}", example: "Linen Edit" },
      { name: "{{look_count}}", example: "24" },
      { name: "{{lookbook_link}}", example: "https://leadnator.app/look/summer" },
    ],
    bodyExample: "",
  },
  {
    id: "m25",
    title: "Live shopping event",
    description: "Live stream invite",
    name: "mkt_live_shopping_01",
    category: "MARKETING",
    language: "en_US",
    body: "🎥 Hi {{customer_name}}! Join our live shopping event on {{event_date}} at {{event_time}}. Exclusive prices + giveaways: {{event_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Karan" },
      { name: "{{event_date}}", example: "25 Apr 2026" },
      { name: "{{event_time}}", example: "8 PM IST" },
      { name: "{{event_link}}", example: "https://leadnator.app/live/abc" },
    ],
    bodyExample: "",
  },
  {
    id: "m26",
    title: "Member-only flash perk",
    description: "Loyalty member exclusive",
    name: "mkt_member_perk_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, members get {{perk_description}} this week. Show this message at checkout or use code {{code}} online.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Sneha" },
      { name: "{{perk_description}}", example: "free express shipping" },
      { name: "{{code}}", example: "MEMBER" },
    ],
    bodyExample: "",
  },
  {
    id: "m27",
    title: "Content drop",
    description: "New blog / podcast / video",
    name: "mkt_content_drop_01",
    category: "MARKETING",
    language: "en_US",
    body: "Fresh from the team — {{content_type}}: \"{{content_title}}\". Read it here: {{content_url}}. Reply with your thoughts!",
    parameterFormat: "named",
    namedParams: [
      { name: "{{content_type}}", example: "Playbook" },
      { name: "{{content_title}}", example: "10 lead-gen hacks for 2026" },
      { name: "{{content_url}}", example: "https://leadnator.app/blog/lead-gen-2026" },
    ],
    bodyExample: "",
  },
  {
    id: "m28",
    title: "Pre-order alert",
    description: "Reserve before launch",
    name: "mkt_preorder_01",
    category: "MARKETING",
    language: "en_US",
    body: "Pre-orders for {{product_name}} are open! Reserve yours by {{deadline}} for {{discount}} off plus free shipping. Reserve: {{link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{product_name}}", example: "Acme Pro Pen" },
      { name: "{{deadline}}", example: "29 Apr 2026" },
      { name: "{{discount}}", example: "20%" },
      { name: "{{link}}", example: "https://leadnator.app/preorder/acme-pro" },
    ],
    bodyExample: "",
  },
  {
    id: "m29",
    title: "Survey participation reward",
    description: "Incentivized feedback",
    name: "mkt_survey_reward_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, take our 2-minute survey and get {{reward}} on your next order: {{survey_link}}. Your input shapes what we build next.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Tanya" },
      { name: "{{reward}}", example: "₹100 store credit" },
      { name: "{{survey_link}}", example: "https://leadnator.app/survey/april" },
    ],
    bodyExample: "",
  },
  {
    id: "m30",
    title: "Anniversary special",
    description: "Brand or customer anniversary",
    name: "mkt_anniversary_01",
    category: "MARKETING",
    language: "en_US",
    body: "🎉 Happy anniversary, {{customer_name}}! It's been {{years}} year(s) — celebrate with {{discount}} off your next order using code {{code}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Raj" },
      { name: "{{years}}", example: "1" },
      { name: "{{discount}}", example: "25%" },
      { name: "{{code}}", example: "ANNIV25" },
    ],
    bodyExample: "",
  },
];

export const AUTHENTICATION_TEMPLATE_EXAMPLES = [
  {
    id: "a1",
    title: "Login OTP (one-time code)",
    description: "Standard sign-in verification",
    name: "auth_login_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "{{otp_code}} is your Leadnator login code. It expires in {{expiry_minutes}} minutes. Don't share this code with anyone.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "482910" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a2",
    title: "Signup verification code",
    description: "New account registration",
    name: "auth_signup_code_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Welcome to {{brand_name}}! Use {{otp_code}} to verify your account. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "738214" },
      { name: "{{expiry_minutes}}", example: "15" },
    ],
    bodyExample: "",
  },
  {
    id: "a3",
    title: "Password reset code",
    description: "Forgot-password verification",
    name: "auth_password_reset_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Your password reset code is {{otp_code}}. It expires in {{expiry_minutes}} minutes. If you didn't request a reset, ignore this message.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "291046" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a4",
    title: "Two-factor authentication",
    description: "2FA second-step code",
    name: "auth_2fa_code_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Two-factor code: {{otp_code}}. Enter it on the {{brand_name}} sign-in screen within {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "554210" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a5",
    title: "Phone number verification",
    description: "Verifies phone ownership",
    name: "auth_phone_verify_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Verify your phone number with code {{otp_code}}. Valid for {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "660471" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a6",
    title: "Payment authorization (3DS)",
    description: "Authorize a transaction",
    name: "auth_payment_3ds_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Authorize your {{amount}} payment to {{merchant_name}} with code {{otp_code}}. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{amount}}", example: "₹2,499" },
      { name: "{{merchant_name}}", example: "Acme Retail" },
      { name: "{{otp_code}}", example: "871290" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a7",
    title: "Withdrawal verification",
    description: "Bank withdrawal confirmation",
    name: "auth_withdrawal_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "To confirm withdrawal of {{amount}} to account {{account_last4}}, enter {{otp_code}}. Expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{amount}}", example: "₹15,000" },
      { name: "{{account_last4}}", example: "•••• 4421" },
      { name: "{{otp_code}}", example: "108234" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a8",
    title: "Device added — confirm",
    description: "New device sign-in detected",
    name: "auth_new_device_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "A new device ({{device_name}}) is trying to sign in to your {{brand_name}} account. Confirm with code {{otp_code}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{device_name}}", example: "iPhone 15 — Mumbai" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "740328" },
    ],
    bodyExample: "",
  },
  {
    id: "a9",
    title: "Email change verification",
    description: "Verifies new email address",
    name: "auth_email_change_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Use code {{otp_code}} to confirm your email change to {{new_email}}. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "920184" },
      { name: "{{new_email}}", example: "user@example.com" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a10",
    title: "Password changed alert",
    description: "Confirms password change",
    name: "auth_password_changed_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Your {{brand_name}} password was changed at {{change_time}}. If this wasn't you, secure your account: {{secure_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{change_time}}", example: "19 Apr 2026, 9:42 AM" },
      { name: "{{secure_link}}", example: "https://leadnator.app/security" },
    ],
    bodyExample: "",
  },
  {
    id: "a11",
    title: "Suspicious login alert",
    description: "Unusual sign-in attempt",
    name: "auth_suspicious_login_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "We detected a sign-in to your {{brand_name}} account from {{location}} on {{device_name}}. If this wasn't you, reset your password now.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{location}}", example: "Bengaluru, India" },
      { name: "{{device_name}}", example: "Chrome on Windows" },
    ],
    bodyExample: "",
  },
  {
    id: "a12",
    title: "Account locked notice",
    description: "Account locked for protection",
    name: "auth_account_locked_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Your {{brand_name}} account is temporarily locked after {{attempts}} failed sign-in attempts. Unlock it here: {{unlock_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{attempts}}", example: "5" },
      { name: "{{unlock_link}}", example: "https://leadnator.app/unlock/abc" },
    ],
    bodyExample: "",
  },
  {
    id: "a13",
    title: "Magic link sign-in",
    description: "Passwordless login link",
    name: "auth_magic_link_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Sign in to {{brand_name}} with this magic link: {{magic_link}}. Link expires in {{expiry_minutes}} minutes and can only be used once.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{magic_link}}", example: "https://leadnator.app/m/xyz" },
      { name: "{{expiry_minutes}}", example: "15" },
    ],
    bodyExample: "",
  },
  {
    id: "a14",
    title: "Backup code verification",
    description: "Recovery code use confirmation",
    name: "auth_backup_code_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "A backup recovery code was just used on your {{brand_name}} account. If this wasn't you, secure your account: {{secure_link}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{secure_link}}", example: "https://leadnator.app/security" },
    ],
    bodyExample: "",
  },
  {
    id: "a15",
    title: "Crypto withdrawal OTP",
    description: "Authorizes crypto withdrawal",
    name: "auth_crypto_withdrawal_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Use code {{otp_code}} to confirm withdrawal of {{amount}} to wallet {{wallet_short}}. Expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "552901" },
      { name: "{{amount}}", example: "0.05 BTC" },
      { name: "{{wallet_short}}", example: "1A1zP1...DivfNa" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a16",
    title: "API key reveal confirmation",
    description: "Authorizes API key reveal",
    name: "auth_api_key_reveal_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Use code {{otp_code}} to confirm revealing API key {{key_label}}. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "318220" },
      { name: "{{key_label}}", example: "Production webhook key" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a17",
    title: "Team invitation verification",
    description: "Confirms team invite acceptance",
    name: "auth_team_invite_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "{{inviter_name}} invited you to join {{team_name}} on {{brand_name}}. Use code {{otp_code}} to accept.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{inviter_name}}", example: "Deepak" },
      { name: "{{team_name}}", example: "Worksdelight Marketing" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "640122" },
    ],
    bodyExample: "",
  },
  {
    id: "a18",
    title: "App authorization (OAuth)",
    description: "Confirms third-party app access",
    name: "auth_oauth_consent_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Authorize {{app_name}} to access your {{brand_name}} account with code {{otp_code}}. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{app_name}}", example: "Zapier" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "478209" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a19",
    title: "Session continuation (re-auth)",
    description: "Asks to re-authenticate",
    name: "auth_reauth_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "For your security, please re-authenticate your {{brand_name}} session with code {{otp_code}}. Expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "920113" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a20",
    title: "Document signature OTP",
    description: "E-sign verification code",
    name: "auth_esign_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "To sign document {{document_name}}, enter {{otp_code}}. The code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{document_name}}", example: "MSA-2026.pdf" },
      { name: "{{otp_code}}", example: "104893" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a21",
    title: "Order pickup OTP",
    description: "Code shown to delivery agent",
    name: "auth_order_pickup_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Share this code with your delivery agent to confirm pickup of order {{order_id}}: {{otp_code}}.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{order_id}}", example: "#88291" },
      { name: "{{otp_code}}", example: "5821" },
    ],
    bodyExample: "",
  },
  {
    id: "a22",
    title: "Refund authorization OTP",
    description: "Confirms refund initiation",
    name: "auth_refund_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Authorize refund of {{amount}} for order {{order_id}} with code {{otp_code}}. Expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{amount}}", example: "₹3,499" },
      { name: "{{order_id}}", example: "#88110" },
      { name: "{{otp_code}}", example: "732401" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a23",
    title: "Address change verification",
    description: "Confirms shipping address change",
    name: "auth_address_change_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Use code {{otp_code}} to confirm address change to {{new_address}}. Expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "418209" },
      { name: "{{new_address}}", example: "221-B, Baker Street, Mumbai 400001" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    bodyExample: "",
  },
  {
    id: "a24",
    title: "Card on file removed",
    description: "Confirms card removal",
    name: "auth_card_removed_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Card {{card_last4}} was removed from your {{brand_name}} account on {{change_time}}. If this wasn't you, secure your account.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{card_last4}}", example: "•••• 1234" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{change_time}}", example: "19 Apr 2026, 10:14 AM" },
    ],
    bodyExample: "",
  },
  {
    id: "a25",
    title: "OTP for high-value transfer",
    description: "Authorizes a large transfer",
    name: "auth_highvalue_transfer_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Authorize transfer of {{amount}} to {{recipient_name}} with code {{otp_code}}. This code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{amount}}", example: "₹1,00,000" },
      { name: "{{recipient_name}}", example: "Acme Pvt Ltd" },
      { name: "{{otp_code}}", example: "892014" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a26",
    title: "Re-verification reminder",
    description: "Asks user to re-verify identity",
    name: "auth_reverify_reminder_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Hi {{customer_name}}, your KYC needs to be re-verified by {{deadline}}. Use code {{otp_code}} to start the process.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{customer_name}}", example: "Anita" },
      { name: "{{deadline}}", example: "30 Apr 2026" },
      { name: "{{otp_code}}", example: "207421" },
    ],
    bodyExample: "",
  },
  {
    id: "a27",
    title: "Security key registered",
    description: "Hardware key paired with account",
    name: "auth_security_key_added_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "A new security key ({{key_label}}) was registered on your {{brand_name}} account at {{change_time}}. If this wasn't you, contact support.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{key_label}}", example: "YubiKey 5C" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{change_time}}", example: "19 Apr 2026, 10:42 AM" },
    ],
    bodyExample: "",
  },
  {
    id: "a28",
    title: "Recovery email confirmation",
    description: "Verifies recovery email change",
    name: "auth_recovery_email_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Use code {{otp_code}} to set {{recovery_email}} as your account recovery email.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{otp_code}}", example: "738201" },
      { name: "{{recovery_email}}", example: "backup@example.com" },
    ],
    bodyExample: "",
  },
  {
    id: "a29",
    title: "Multi-account switch OTP",
    description: "Switching between linked accounts",
    name: "auth_account_switch_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Switch to account {{account_label}} with code {{otp_code}}. Code expires in {{expiry_minutes}} minutes.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{account_label}}", example: "Worksdelight Admin" },
      { name: "{{otp_code}}", example: "664210" },
      { name: "{{expiry_minutes}}", example: "5" },
    ],
    bodyExample: "",
  },
  {
    id: "a30",
    title: "Webhook secret rotation",
    description: "Confirms webhook secret rotation",
    name: "auth_webhook_rotate_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "Confirm rotating your {{brand_name}} webhook secret with code {{otp_code}}. Existing integrations may need to be updated.",
    parameterFormat: "named",
    namedParams: [
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{otp_code}}", example: "910382" },
    ],
    bodyExample: "",
  },
];

export const CTA_TEMPLATE_EXAMPLES = [
  {
    id: "c1",
    title: "Visit website (URL CTA)",
    description: "Marketing template with a 'Shop now' link button",
    name: "cta_visit_website_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, our new {{collection_name}} is live! Tap below to browse the full {{look_count}}-piece edit.",
    namedParams: [
      { name: "{{customer_name}}", example: "Anita" },
      { name: "{{collection_name}}", example: "Summer 2026" },
      { name: "{{look_count}}", example: "24" },
    ],
    buttons: [
      { type: "URL", text: "Shop now", url: "https://leadnator.app/shop" },
    ],
  },
  {
    id: "c2",
    title: "Call us back (Phone CTA)",
    description: "Utility template with a phone-call button",
    name: "cta_call_us_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, we tried reaching you about {{topic}}. Tap to call us back at your convenience.",
    namedParams: [
      { name: "{{customer_name}}", example: "Rohit" },
      { name: "{{topic}}", example: "your loan application" },
    ],
    buttons: [
      { type: "PHONE_NUMBER", text: "Call us back", phone_number: "+919876543210" },
    ],
  },
  {
    id: "c3",
    title: "Copy promo code (Copy CTA)",
    description: "Marketing template with a copy-to-clipboard code button",
    name: "cta_copy_code_01",
    category: "MARKETING",
    language: "en_US",
    body: "🎁 Hi {{customer_name}}! Get {{discount}} off your next order with this exclusive code. Tap to copy and paste at checkout.",
    namedParams: [
      { name: "{{customer_name}}", example: "Priya" },
      { name: "{{discount}}", example: "30%" },
    ],
    buttons: [
      { type: "COPY_CODE", text: "Copy code", example: ["WELCOME30"] },
    ],
  },
  {
    id: "c4",
    title: "Track order (URL + Quick reply)",
    description: "Utility — track button + 'Need help?' quick reply",
    name: "cta_track_order_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your order {{order_id}} is on the way. Tap below to track it live.",
    namedParams: [
      { name: "{{customer_name}}", example: "Karan" },
      { name: "{{order_id}}", example: "#88301" },
    ],
    buttons: [
      { type: "URL", text: "Track order", url: "https://leadnator.app/track/{{order_id}}" },
      { type: "QUICK_REPLY", text: "Need help?" },
    ],
  },
  {
    id: "c5",
    title: "Book a demo (URL CTA)",
    description: "Lead-gen template with a calendar booking link",
    name: "cta_book_demo_01",
    category: "MARKETING",
    language: "en_US",
    body: "Hi {{customer_name}}, ready to see {{product_name}} in action? Book a free 15-min demo with our team.",
    namedParams: [
      { name: "{{customer_name}}", example: "Vivek" },
      { name: "{{product_name}}", example: "Leadnator Pro" },
    ],
    buttons: [
      { type: "URL", text: "Book a demo", url: "https://leadnator.app/book/demo" },
    ],
  },
  {
    id: "c6",
    title: "Pay invoice (URL CTA)",
    description: "Utility — secure payment link button",
    name: "cta_pay_invoice_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, your invoice {{invoice_id}} of {{amount}} is due on {{due_date}}. Pay securely below.",
    namedParams: [
      { name: "{{customer_name}}", example: "Mohit" },
      { name: "{{invoice_id}}", example: "INV-2026-042" },
      { name: "{{amount}}", example: "₹2,499" },
      { name: "{{due_date}}", example: "5 May 2026" },
    ],
    buttons: [
      { type: "URL", text: "Pay now", url: "https://leadnator.app/pay/{{invoice_id}}" },
    ],
  },
  {
    id: "c7",
    title: "Confirm appointment (2 quick replies)",
    description: "Utility — confirm/reschedule appointment with quick replies",
    name: "cta_confirm_appointment_01",
    category: "UTILITY",
    language: "en_US",
    body: "Hi {{customer_name}}, you have an appointment on {{date}} at {{time}}. Please confirm or let us know if you'd like to reschedule.",
    namedParams: [
      { name: "{{customer_name}}", example: "Sneha" },
      { name: "{{date}}", example: "8 May 2026" },
      { name: "{{time}}", example: "3:00 PM" },
    ],
    buttons: [
      { type: "QUICK_REPLY", text: "Confirm" },
      { type: "QUICK_REPLY", text: "Reschedule" },
      { type: "QUICK_REPLY", text: "Cancel" },
    ],
  },
  {
    id: "c8",
    title: "Verify OTP (Copy code CTA)",
    description: "Authentication — copy OTP button (no link to phishing)",
    name: "cta_verify_otp_01",
    category: "AUTHENTICATION",
    language: "en_US",
    body: "{{otp_code}} is your {{brand_name}} verification code. It expires in {{expiry_minutes}} minutes. Tap below to copy.",
    namedParams: [
      { name: "{{otp_code}}", example: "482910" },
      { name: "{{brand_name}}", example: "Leadnator" },
      { name: "{{expiry_minutes}}", example: "10" },
    ],
    buttons: [
      { type: "COPY_CODE", text: "Copy code", example: ["482910"] },
    ],
  },
];

export const ALL_TEMPLATE_EXAMPLES = [
  ...UTILITY_TEMPLATE_EXAMPLES,
  ...MARKETING_TEMPLATE_EXAMPLES,
  ...AUTHENTICATION_TEMPLATE_EXAMPLES,
  ...CTA_TEMPLATE_EXAMPLES,
];

export function getTemplateExampleById(id) {
  if (!id) return null;
  return ALL_TEMPLATE_EXAMPLES.find((x) => x.id === String(id).trim()) || null;
}

/** Map example to CreateTemplatePage form shape */
export function exampleToFormState(ex) {
  if (!ex) return null;
  return {
    name: ex.name,
    category: ex.category,
    language: ex.language || "en_US",
    body: ex.body,
    parameterFormat: ex.parameterFormat || "named",
    namedParams: Array.isArray(ex.namedParams) ? ex.namedParams.map((p) => ({ ...p })) : [],
    bodyExample: ex.bodyExample || "",
  };
}
