// All countries with ISO-2 code (for flags via flagcdn) and dial code.
// code = numeric dial code (no '+'). Used as the WhatsApp number prefix.
export const COUNTRY_CODES = [
  { name: "Afghanistan", cc: "af", code: "93" },
  { name: "Albania", cc: "al", code: "355" },
  { name: "Algeria", cc: "dz", code: "213" },
  { name: "Andorra", cc: "ad", code: "376" },
  { name: "Angola", cc: "ao", code: "244" },
  { name: "Argentina", cc: "ar", code: "54" },
  { name: "Armenia", cc: "am", code: "374" },
  { name: "Australia", cc: "au", code: "61" },
  { name: "Austria", cc: "at", code: "43" },
  { name: "Azerbaijan", cc: "az", code: "994" },
  { name: "Bahamas", cc: "bs", code: "1242" },
  { name: "Bahrain", cc: "bh", code: "973" },
  { name: "Bangladesh", cc: "bd", code: "880" },
  { name: "Barbados", cc: "bb", code: "1246" },
  { name: "Belarus", cc: "by", code: "375" },
  { name: "Belgium", cc: "be", code: "32" },
  { name: "Belize", cc: "bz", code: "501" },
  { name: "Benin", cc: "bj", code: "229" },
  { name: "Bhutan", cc: "bt", code: "975" },
  { name: "Bolivia", cc: "bo", code: "591" },
  { name: "Bosnia and Herzegovina", cc: "ba", code: "387" },
  { name: "Botswana", cc: "bw", code: "267" },
  { name: "Brazil", cc: "br", code: "55" },
  { name: "Brunei", cc: "bn", code: "673" },
  { name: "Bulgaria", cc: "bg", code: "359" },
  { name: "Burkina Faso", cc: "bf", code: "226" },
  { name: "Burundi", cc: "bi", code: "257" },
  { name: "Cambodia", cc: "kh", code: "855" },
  { name: "Cameroon", cc: "cm", code: "237" },
  { name: "Canada", cc: "ca", code: "1" },
  { name: "Cape Verde", cc: "cv", code: "238" },
  { name: "Central African Republic", cc: "cf", code: "236" },
  { name: "Chad", cc: "td", code: "235" },
  { name: "Chile", cc: "cl", code: "56" },
  { name: "China", cc: "cn", code: "86" },
  { name: "Colombia", cc: "co", code: "57" },
  { name: "Comoros", cc: "km", code: "269" },
  { name: "Congo", cc: "cg", code: "242" },
  { name: "Congo (DRC)", cc: "cd", code: "243" },
  { name: "Costa Rica", cc: "cr", code: "506" },
  { name: "Croatia", cc: "hr", code: "385" },
  { name: "Cuba", cc: "cu", code: "53" },
  { name: "Cyprus", cc: "cy", code: "357" },
  { name: "Czechia", cc: "cz", code: "420" },
  { name: "Denmark", cc: "dk", code: "45" },
  { name: "Djibouti", cc: "dj", code: "253" },
  { name: "Dominican Republic", cc: "do", code: "1809" },
  { name: "Ecuador", cc: "ec", code: "593" },
  { name: "Egypt", cc: "eg", code: "20" },
  { name: "El Salvador", cc: "sv", code: "503" },
  { name: "Equatorial Guinea", cc: "gq", code: "240" },
  { name: "Eritrea", cc: "er", code: "291" },
  { name: "Estonia", cc: "ee", code: "372" },
  { name: "Eswatini", cc: "sz", code: "268" },
  { name: "Ethiopia", cc: "et", code: "251" },
  { name: "Fiji", cc: "fj", code: "679" },
  { name: "Finland", cc: "fi", code: "358" },
  { name: "France", cc: "fr", code: "33" },
  { name: "Gabon", cc: "ga", code: "241" },
  { name: "Gambia", cc: "gm", code: "220" },
  { name: "Georgia", cc: "ge", code: "995" },
  { name: "Germany", cc: "de", code: "49" },
  { name: "Ghana", cc: "gh", code: "233" },
  { name: "Greece", cc: "gr", code: "30" },
  { name: "Greenland", cc: "gl", code: "299" },
  { name: "Guatemala", cc: "gt", code: "502" },
  { name: "Guinea", cc: "gn", code: "224" },
  { name: "Guyana", cc: "gy", code: "592" },
  { name: "Haiti", cc: "ht", code: "509" },
  { name: "Honduras", cc: "hn", code: "504" },
  { name: "Hong Kong", cc: "hk", code: "852" },
  { name: "Hungary", cc: "hu", code: "36" },
  { name: "Iceland", cc: "is", code: "354" },
  { name: "India", cc: "in", code: "91" },
  { name: "Indonesia", cc: "id", code: "62" },
  { name: "Iran", cc: "ir", code: "98" },
  { name: "Iraq", cc: "iq", code: "964" },
  { name: "Ireland", cc: "ie", code: "353" },
  { name: "Israel", cc: "il", code: "972" },
  { name: "Italy", cc: "it", code: "39" },
  { name: "Ivory Coast", cc: "ci", code: "225" },
  { name: "Jamaica", cc: "jm", code: "1876" },
  { name: "Japan", cc: "jp", code: "81" },
  { name: "Jordan", cc: "jo", code: "962" },
  { name: "Kazakhstan", cc: "kz", code: "7" },
  { name: "Kenya", cc: "ke", code: "254" },
  { name: "Kuwait", cc: "kw", code: "965" },
  { name: "Kyrgyzstan", cc: "kg", code: "996" },
  { name: "Laos", cc: "la", code: "856" },
  { name: "Latvia", cc: "lv", code: "371" },
  { name: "Lebanon", cc: "lb", code: "961" },
  { name: "Lesotho", cc: "ls", code: "266" },
  { name: "Liberia", cc: "lr", code: "231" },
  { name: "Libya", cc: "ly", code: "218" },
  { name: "Liechtenstein", cc: "li", code: "423" },
  { name: "Lithuania", cc: "lt", code: "370" },
  { name: "Luxembourg", cc: "lu", code: "352" },
  { name: "Macau", cc: "mo", code: "853" },
  { name: "Madagascar", cc: "mg", code: "261" },
  { name: "Malawi", cc: "mw", code: "265" },
  { name: "Malaysia", cc: "my", code: "60" },
  { name: "Maldives", cc: "mv", code: "960" },
  { name: "Mali", cc: "ml", code: "223" },
  { name: "Malta", cc: "mt", code: "356" },
  { name: "Mauritania", cc: "mr", code: "222" },
  { name: "Mauritius", cc: "mu", code: "230" },
  { name: "Mexico", cc: "mx", code: "52" },
  { name: "Moldova", cc: "md", code: "373" },
  { name: "Monaco", cc: "mc", code: "377" },
  { name: "Mongolia", cc: "mn", code: "976" },
  { name: "Montenegro", cc: "me", code: "382" },
  { name: "Morocco", cc: "ma", code: "212" },
  { name: "Mozambique", cc: "mz", code: "258" },
  { name: "Myanmar", cc: "mm", code: "95" },
  { name: "Namibia", cc: "na", code: "264" },
  { name: "Nepal", cc: "np", code: "977" },
  { name: "Netherlands", cc: "nl", code: "31" },
  { name: "New Zealand", cc: "nz", code: "64" },
  { name: "Nicaragua", cc: "ni", code: "505" },
  { name: "Niger", cc: "ne", code: "227" },
  { name: "Nigeria", cc: "ng", code: "234" },
  { name: "North Korea", cc: "kp", code: "850" },
  { name: "North Macedonia", cc: "mk", code: "389" },
  { name: "Norway", cc: "no", code: "47" },
  { name: "Oman", cc: "om", code: "968" },
  { name: "Pakistan", cc: "pk", code: "92" },
  { name: "Palestine", cc: "ps", code: "970" },
  { name: "Panama", cc: "pa", code: "507" },
  { name: "Papua New Guinea", cc: "pg", code: "675" },
  { name: "Paraguay", cc: "py", code: "595" },
  { name: "Peru", cc: "pe", code: "51" },
  { name: "Philippines", cc: "ph", code: "63" },
  { name: "Poland", cc: "pl", code: "48" },
  { name: "Portugal", cc: "pt", code: "351" },
  { name: "Qatar", cc: "qa", code: "974" },
  { name: "Romania", cc: "ro", code: "40" },
  { name: "Russia", cc: "ru", code: "7" },
  { name: "Rwanda", cc: "rw", code: "250" },
  { name: "Saudi Arabia", cc: "sa", code: "966" },
  { name: "Senegal", cc: "sn", code: "221" },
  { name: "Serbia", cc: "rs", code: "381" },
  { name: "Seychelles", cc: "sc", code: "248" },
  { name: "Sierra Leone", cc: "sl", code: "232" },
  { name: "Singapore", cc: "sg", code: "65" },
  { name: "Slovakia", cc: "sk", code: "421" },
  { name: "Slovenia", cc: "si", code: "386" },
  { name: "Somalia", cc: "so", code: "252" },
  { name: "South Africa", cc: "za", code: "27" },
  { name: "South Korea", cc: "kr", code: "82" },
  { name: "South Sudan", cc: "ss", code: "211" },
  { name: "Spain", cc: "es", code: "34" },
  { name: "Sri Lanka", cc: "lk", code: "94" },
  { name: "Sudan", cc: "sd", code: "249" },
  { name: "Suriname", cc: "sr", code: "597" },
  { name: "Sweden", cc: "se", code: "46" },
  { name: "Switzerland", cc: "ch", code: "41" },
  { name: "Syria", cc: "sy", code: "963" },
  { name: "Taiwan", cc: "tw", code: "886" },
  { name: "Tajikistan", cc: "tj", code: "992" },
  { name: "Tanzania", cc: "tz", code: "255" },
  { name: "Thailand", cc: "th", code: "66" },
  { name: "Togo", cc: "tg", code: "228" },
  { name: "Trinidad and Tobago", cc: "tt", code: "1868" },
  { name: "Tunisia", cc: "tn", code: "216" },
  { name: "Turkey", cc: "tr", code: "90" },
  { name: "Turkmenistan", cc: "tm", code: "993" },
  { name: "Uganda", cc: "ug", code: "256" },
  { name: "Ukraine", cc: "ua", code: "380" },
  { name: "United Arab Emirates", cc: "ae", code: "971" },
  { name: "United Kingdom", cc: "gb", code: "44" },
  { name: "United States", cc: "us", code: "1" },
  { name: "Uruguay", cc: "uy", code: "598" },
  { name: "Uzbekistan", cc: "uz", code: "998" },
  { name: "Venezuela", cc: "ve", code: "58" },
  { name: "Vietnam", cc: "vn", code: "84" },
  { name: "Yemen", cc: "ye", code: "967" },
  { name: "Zambia", cc: "zm", code: "260" },
  { name: "Zimbabwe", cc: "zw", code: "263" },
];

export const findCountry = (cc) => COUNTRY_CODES.find((c) => c.cc === cc) || COUNTRY_CODES.find((c) => c.cc === "in");
